apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: process1
spec:
  output:
    to:
      kind: ImageStreamTag
      name: process1:latest
  source:
    dockerfile: |
      FROM python:3.10
      WORKDIR /app
      COPY . .
      RUN apt-get update && apt-get install -y vim && pip install -r requirements.txt
      CMD ["python", "process1.py"]
  strategy:
    type: Docker
