data_stores: {}
  # minio: 
  #   - host: minio
  #     username: miniouser
  #     password: miniopass
  #     port: 9000

brokers:
  - host: broker_host
    username: postman
    password: password
    port: 30011
    protocol: mqtt3.1.1

hierarchy:
  organization: hello-olcf
  facility: olcf
  system: hello-olcf-system
  subsystem: hello-olcf-subsystem
  service: hello-olcf-service

client_config:
  destination: hello-olcf.olcf.hello-olcf-system.hello-olcf-subsystem.hello-olcf-service
  operation: IntersectS3M.run_compute_job
